### ISSUE TITLE
uSIF vs Averaging

### ISSUE THREAD

**Issue by fros1y** [yumeng5/Spherical-Text-Embedding#10]
I noticed that you are calculating sentence embedding using an average of the individual word vectors when performing clustering, etc.  Did you happen to evaluate whether SIF or uSIF would be advantageous over averaging?

**Comment by yumeng5** [comment]
Hi,

Thanks for the question. Are you referring to the following functions in the evaluation code?
https://github.com/yumeng5/Spherical-Text-Embedding/blob/b0f88207189373d0500208ddacf46aa9c2bbd9da/cluster.py#L82

https://github.com/yumeng5/Spherical-Text-Embedding/blob/b0f88207189373d0500208ddacf46aa9c2bbd9da/classify.py#L32-L35

For baselines that produce document/sentence embeddings (like SIF and JoSE), we directly take their document/sentence embeddings as features for clustering/classification. The above functions (averaged word embedding) are used to produce sentence embeddings only for word embedding baselines (word2vec) that cannot naturally learn sentence representations. They are actually not used anywhere in the evaluation code (I should have deleted them to avoid confusion).

Please let me know if you have any further questions!

Best,
Yu

**Comment by fros1y** [comment]
Thanks, but I think I'm confused now about the results in the paper for document/sentence embedding.  

JoSE is compared to word2vec-based word embeddings, composed together with averaging, and unspecified word embeddings (word2vec again?), composed together with SIF.  

When reporting sentence/document performance, are the JoSE-based word embeddings composed together using averaging, or composed together using SIF?  In the code, it looks like just averaged JoSE-based word embeddings.  Is that correct? 

Thanks!
