### ISSUE TITLE
Is it applicable to other data?

### ISSUE THREAD

**Issue by hyungsseop** [yumeng5/Spherical-Text-Embedding#14]
Hi, 

Is it applicable to other datasets such as router and webkb?

If possible, I wonder if the parameter setting is the same.

If i need to set other parameters, I would appreciate it if you could let me know how to set them.

thank you!

**Comment by yumeng5** [comment]
Hi @hyungsseop ,

I believe you don't need to change many parameters when running the code to obtain embeddings on other corpora. It might help to change the number of iterations and minimum word count threshold based on the statistics of your corpus (e.g., for smaller corpora, set a bigger `iter` and smaller `min_count`). Other than those, you could use the default parameter values.

Best,
Yu
