### ISSUE TITLE
Can you provide the pretrained word embeddings?

### ISSUE THREAD

**Issue by qianc62** [yumeng5/Spherical-Text-Embedding#2]
Very interesting work. Can you provide the pretrained word embeddings (as GloVe does)? So that readers can use it without re-training.

**Comment by yumeng5** [comment]
Hi Chen,

Thanks for your suggestions. We have released the pre-trained embeddings whose links can be found in the README file of the repo. Please let me know if you have any further concerns/questions!

Best,
Yu
