### ISSUE TITLE
[Question] What does '<\s>' in vocabulary means?

### ISSUE THREAD

**Issue by hapoyige** [yumeng5/Spherical-Text-Embedding#3]
Hi, yumeng, Thanks for your interesting work!  
After running your code, I seem got a special word in the generated vocabulary and its frequence is equal to the number of my documents. Does this mean '\n' or something else? Does this influence the training ? Thank you in advance.

**Comment by yumeng5** [comment]
Hi,

Thanks for the question. Yes, the ``</s>`` token is the end-of-sentence token and will always appear at the first word in the vocabulary. The following code refers to where ``\n`` is converted into ``</s>``.
https://github.com/yumeng5/Spherical-Text-Embedding/blob/0e572b8f2fc911deecb6b52de735d92ac891eea9/src/jose.c#L70-L72
The ``</s>`` token is designed to mark where the sentence ends, so it is completely normal to include it in training. However, after training, you can completely ignore it and use other meaningful word embeddings in the downstream tasks.

Please let me know if you have any further questions!

Best,
Yu

**Comment by hapoyige** [comment]
Detail explanation! Thank you, I got it.
