### ISSUE TITLE
Faulty Memory Management in Implementation of Hash Table with Linear Probing

### ISSUE THREAD

**Issue by daskol** [yumeng5/Spherical-Text-Embedding#6]
Adding a new word to vocabulary could cause in segmentation fault as vocabulary grows. The reason is that only `vocab` array is reallocated `vocab_hash` array remains untouched.

**Comment by daskol** [comment]
I think that the best solution for the issue would be removing the reallocation and introducing option to specify expetected vocabulary size.

**Comment by yumeng5** [comment]
Hi,

Thanks for the comment. You are right that the size of ``vocab_hash`` is hard-coded as a fixed constant at the beginning of the file.
https://github.com/yumeng5/Spherical-Text-Embedding/blob/b0f88207189373d0500208ddacf46aa9c2bbd9da/src/jose.c#L17
So if you have an extremely large vocabulary, a simple solution is to modify the constant here to have a large enough ``vocab_hash_size``.

Similarly, as you proposed, we can remove the reallocation of the ``vocab`` array part and set its maximum size to be equal to that of ``vocab_hash``. However, you will need to allocate that much memory to the ``vocab`` array regardless of how small the corpus might be. The reallocation procedure serves as a way to dynamically fit to the vocabulary of the real corpus, thus improving the memory efficiency of the code.

If you do not care about memory issues at all, then you can absolutely remove the reallocation part. However, to make the code generally more memory-efficient, I would like to keep the reallocation part for now.

Please let me know if you have any further suggestions!

Best,
Yu
