### ISSUE TITLE
Licensing

### ISSUE THREAD

**Issue by daskol** [yumeng5/Spherical-Text-Embedding#7]
The source code in [src/jose.c](src/jose.c) looks pretty similary to original [word2vec](https://github.com/tmikolov/word2vec) imlementation by Mikolov. Since word2vec sources is distributed under Apache-2 terms, it would be greate to satisfy [redistribution condition](https://github.com/tmikolov/word2vec/blob/master/LICENSE#L90-L129).

**Comment by yumeng5** [comment]
Hi,

Thanks for the reminder. I have added redistribution notices to the README file and the source file. Please let me know if you have any further concerns!

Best,
Yu
